services:
  budgetbook-server:
    image: ghcr.io/sirmrmanuel0/budgetbook:latest
    container_name: budgetbook-server
    working_dir: /app
    ports:
      - localhost:443:443 # Change ip and port here e.g. 192.168.178.100:80:443 the last :443 must ALWAYS exist
    volumes:
      - ./data:/permanent_storage
      - ./cert:/cert_pub
    command: python main.py --mode server --ip 0.0.0.0 --port 443
