name: Build Linux wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12, 3.13 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add cargo to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp312-manylinux_* cp313-manylinux_*"
          CIBW_BEFORE_BUILD: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . $HOME/.cargo/env
          CIBW_ENVIRONMENT: "RUSTFLAGS='-C target-cpu=native'"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: wheelhouse
