name: Docker Cargo Test Workflow

on:
  push:
    branches:
      - '**'

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_base:
    name: Base Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - working-directory: ./base_backend
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  build_and_test_apps:
    name: App Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        apps:
          - agent_mo
    steps:
      - uses: actions/checkout@v4
      - working-directory: ./apps/${{ matrix.apps }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd apps/${{ matrix.apps }}/backend
      - run: cargo build --verbose
      - run: cargo test --verbose  
