name: Pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and activate virtual environment
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install -r requirements.txt
    - name: Install build-dependencies and build
      run: |
        #!/usr/bin/env bash
        set -e

        echo "=== Rust installieren ==="
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"

        echo "=== Python & Pip prüfen ==="
        python --version
        pip --version

        echo "=== Maturin installieren ==="
        pip install --upgrade pip
        pip install maturin

        echo "=== Projekt mit Maturin bauen ==="
        maturin develop --release
    - name: Test with pytest
      run: |
        which python
        pytest
